version: '3.8'

services:
  frontend:
    build:
      context: ./itb-front
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - itb-net

  backend:
    build:
      context: ./itb-back
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/itb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql@sit
    depends_on:
      - db
    networks:
      - itb-net

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: itb
      MYSQL_ROOT_PASSWORD: mysql@sit
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - itb-net

volumes:
  db-data:

networks:
  itb-net:
