# Stage 1: Build the Vue application
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the built application using Nginx with custom config
FROM nginx:alpine
RUN mkdir /app
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/itb-front.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
